# Site
title: blog.Eumeryx
subtitle: ''
description: ''
keywords:
author: Eumeryx
language: en
timezone: 'Asia/Shanghai'

# URL
url: https://blog.eumeryx.link
root: /
permalink: /posts/:year:month:day:hour:minute/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - js/**/*
  - css/**/*
  - emojis/**/*

# Writing
new_post_name: :title.md
default_layout: draft
titlecase: true
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/

archive_generator:
  per_page: 20
  yearly: false
  monthly: false
  daily: false

tag_generator:
  enable_index_page: true
  tag_dir: /tags/

### marked
marked:
  gfm: true
  breaks: false
  mangle: true
  pedantic: false
  smartLists: true
  smartypants: true
  headerIds: true
  headerPrefix: ''

## Html minifier
html_minifier:  
  collapseBooleanAttributes: true
  collapseWhitespace: true
  # Ignore '<!-- more -->' https://hexo.io/docs/tag-plugins#Post-Excerpt
  #ignoreCustomComments: [ !!js/regexp /^\s*more/]
  removeComments: true
  removeAttributeQuotes: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true

## Themes: https://hexo.io/themes/
theme: Apollo++
theme_config:
  startyear: 2021
  comment: waline
  comment_auto_load: false
  waline:
    client: '/js/waline/waline.esm.js'
    serverURL: 'https://waline.eumeryx.link'
    options:
      imageUploader: false
      search: false
      emoji: 
        - /emojis/tw-emoji
      locale:
        placeholder: Support markdown and KaTeX.

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Eumeryx/Eumeryx.github.io.git
  branch: public
